# Generated by Django 5.0.6 on 2024-06-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('AÇÃO', 'Análises'), ('TERROR', 'Programação'), ('DOCUMENTARIOS', 'Apresentação'), ('ROMANCE', 'Romance'), ('COMÉDIA', 'Comédia'), ('FANTASIA', 'Fantasia'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
